---
  
- name: Ensure the roles and users exist in tomcat-users.xml
  xml:
    path: "{{ ansible_env.CATALINA_HOME }}/conf/tomcat-users.xml"
    namespaces:
      tomcat: "http://tomcat.apache.org/xml"
    xpath: "/tomcat:tomcat-users"
    set_children:
      - role:
          rolename: manager-gui
      - user:
          username: tomcat
          password: s3cret  #add your password here
          roles: manager-gui

         
- name: Check if app already deployed
  stat:  
    path: "{{ ansible_env.CATALINA_HOME }}/webapps/petclinic.war"
  register: petclinic_file

- name: Remove old WAR
  file:
    path: "{{ ansible_env.CATALINA_HOME }}/webapps/petclinic.war"
    state: absent
  when: petclinic_file.stat.exists
  
- name: Deploy petclinic  
  copy: 
    src: "{{ ansible_env.HOME }}/Workshop2/spring-petclinic/target/petclinic.war"
    dest: "{{ ansible_env.CATALINA_HOME }}/webapps/petclinic.war"
  

- name: Change Tomcat Port to 9090
  xml:
    path: "{{ ansible_env.CATALINA_HOME }}/conf/server.xml"
    xpath: "/Server/Service/Connector[@port='8080']"
    attribute: port
    value: "9090"
  notify:
   - restart tomcat
      

