---
- hosts: tomcat
  tasks:
   - name: Start Tomcat
     shell: "nohup {{ ansible_env.CATALINA_HOME }}/bin/startup.sh &"
    
   - name: Wait for Tomcat to fully start
     wait_for:
       path: "{{ ansible_env.CATALINA_HOME }}/logs/catalina.out"
       search_regex: "Server startup in"
       timeout: 60

   - name: Check if PetClinic WAR is deployed
     stat:
       path: "{{ ansible_env.CATALINA_HOME }}/webapps/petclinic.war"
     register: petclinic_war
     failed_when: not petclinic_war.stat.exists
   
   - name: Check if PetClinic application accessible
     uri:
       url: "http://localhost:9090/petclinic/"
       method: GET
       status_code: 200
     register: petclinic_status
     retries: 10
     delay: 5
     until: petclinic_status.status == 200

   - name: Confirm PetClinic is accessible
     debug:
       msg: "PetClinic is deployed successfully and accessible!"

