---
- name: stop nagios
  listen: restart nagios
  shell: "pgrep -f '[n]agios' || killall nagios"

- name: start nagios
  listen: restart nagios
  shell: "! pgrep -f '[n]agios' || nohup {{ ansible_env.HOME }}/nagios/bin/nagios {{ ansible_env.HOME }}/nagios/etc/nagios.cfg &"

