---
- name: stop tomcat
  listen:
    - restart tomcat
    - stop tomcat
  shell: "! pgrep -f '[c]atalina' || {{ ansible_env.CATALINA_HOME }}/bin/shutdown.sh"
    

- name: start tomcat
  listen: 
    - restart tomcat
    - start tomcat
  shell: "pgrep -f '[c]atalina' || nohup {{ ansible_env.CATALINA_HOME }}/bin/startup.sh &"

